"""
feature_extraction.py  -  generic STL -> geometric-features extractor
=====================================================================
Extracts ML-ready geometric features from every STL in a folder.
Works for ANY lattice STL dataset (ADMS, TPMS, ...).

USERS DO NOT EDIT THIS FILE.
All settings live in ML_settings.xlsx (created automatically on first
run, next to this script). Open it in Excel, edit the values, save,
run again - same workflow as runs_input.xlsx for the simulations.

Design rules (Alex / MECH0100, 18-07-2026):
  * Label-free: STLs in -> features CSV out. FEA labels joined separately.
  * All shape features DIMENSIONLESS (scaled by cell size) so datasets
    with different cell sizes (ADMS 3 mm vs TPMS 10 mm) are comparable.
  * Deterministic (fixed seed), resume-safe (skips files already done).
  * No fragile deps: curvature computed from first principles
    (angle defect / dihedral angles), thickness via opposite-normal
    KD-tree search (cannot shoot through pores). Only numpy/scipy/trimesh-load.
  * Self-validating: thickness_ratio column ~= 1.0 proves the features
    describe the geometry we think they do.

Run:  double-click RUN_FEATURES.bat
"""

import os, re, csv, sys, time
import numpy as np

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

def _find_settings(base, name="ML_settings.xlsx"):
    """Locate the settings workbook.

    Scripts live in ML/scripts/ but the workbook sits one level up in ML/ so
    the user sees it immediately. Checking the parent too means the layout can
    change (or a user can keep the workbook beside the scripts) without edits.
    """
    import os as _os
    here = _os.path.join(base, name)
    if _os.path.exists(here):
        return here
    up = _os.path.join(_os.path.dirname(base), name)
    return up if _os.path.exists(up) else here

SETTINGS_XLSX = _find_settings(SCRIPT_DIR)

# Relative paths in the settings workbook resolve against the folder that HOLDS
# the workbook, NOT against this file. That way the scripts can be moved into a
# subfolder (ML/scripts/) without touching a single setting.
BASE_DIR = os.path.dirname(SETTINGS_XLSX)
import sys; sys.path.insert(0, SCRIPT_DIR); import run_paths   # clean filing: data/ + runs/


# ------------------------------------------------------------------
# settings workbook (auto-created with defaults; user edits in Excel)
# ------------------------------------------------------------------
# Paths may be absolute, or relative to this script's folder (preferred - keeps
# the toolchain portable between users).
DEFAULTS = [
    ("stl_folder",  r"../ADMS/ADMS_STL",
     "Folder containing the .stl files (relative to ML_settings.xlsx folder, or absolute)"),
    ("output_csv",  r"outputs/features_ADMS.csv",
     "Where the feature table is written (appends / resumes)"),
    ("dataset_tag", "ADMS", "Written into every row (e.g. ADMS / TPMS)"),
    ("cell_size_mm", 3.0, "Unit-cell size: ADMS=3.0, Zhezhe TPMS=10.0"),
    ("thickness_convention", "total",
     "How filename t relates to wall: total (wall=t, ADMS) | double (wall=2t, TPMS level-set) | none"),
    ("n_sample_points", 4000, "Surface samples for thickness stats"),
    ("random_seed", 42, "Do NOT change mid-dataset (reproducibility)"),
    ("boundary_skin_frac", 0.02,
     "Exclude this fraction of bbox at the faces (cut faces pollute curvature)"),
    ("max_file_mb", 500, "Skip STLs larger than this"),
    # --- nothing below is specific to ADMS; change for your own filenames ---
    ("filename_params",
     r"inner:i(\d+)p(\d+); density:d(\d+)p(\d+); t:t(\d+)p(\d+); "
     r"seed:_s(\d+); multi:m(\d+)p(\d+)",
     "How to read design parameters out of the filename: 'slot:regex; ...'. "
     "Slots: inner, density, t, seed, multi. Two capture groups -> g1.g2 "
     "(22p85 -> 22.85); one group -> literal. Unmatched slots stay blank."),
    ("thickness_cap_factor", 3.0,
     "Thickness search stops at this multiple of the expected wall. Raise if "
     "your walls vary a lot; lower to reject pore-crossing hits."),
    ("thickness_cap_fallback", 0.6,
     "Used instead when the filename gives no t: cap = this * cell_size_mm"),
    ("min_thickness_hits", 50,
     "Fewest valid thickness samples before the thickness columns are left blank"),
    ("normal_axis_tol", 0.9,
     "Fabric tensor: |n.axis| above this counts as axis-aligned, used to drop "
     "the cube's flat cut faces. 1.0 = only exactly aligned."),
]

# Fallback if the setting is blank. ADMS naming; harmless for other schemes
# because unmatched slots simply stay empty.
DEFAULT_FILENAME_PARAMS = (
    r"inner:i(\d+)p(\d+); density:d(\d+)p(\d+); t:t(\d+)p(\d+); "
    r"seed:_s(\d+); multi:m(\d+)p(\d+)"
)


def load_settings():
    import openpyxl
    if not os.path.exists(SETTINGS_XLSX):
        wb = openpyxl.Workbook()
        ws = wb.active; ws.title = "settings"
        ws.append(["setting", "value", "explanation"])
        from openpyxl.styles import Font, PatternFill
        for c in ws[1]:
            c.font = Font(bold=True, color="FFFFFF")
            c.fill = PatternFill("solid", fgColor="500778")
        for k, v, note in DEFAULTS:
            ws.append([k, v, note])
        ws.column_dimensions["A"].width = 24
        ws.column_dimensions["B"].width = 70
        ws.column_dimensions["C"].width = 60
        wb.save(SETTINGS_XLSX)
        print(f"[first run] created {SETTINGS_XLSX}")
        print("Open it in Excel, check the values (especially stl_folder), "
              "save, then run this again.")
        sys.exit(0)
    wb = openpyxl.load_workbook(SETTINGS_XLSX, data_only=True)
    # profile-aware: ML_PROFILE=TPMS reads sheet `settings_TPMS` when it exists,
    # so the STL folder / cell size / thickness convention live in the workbook
    # and never in a .bat. Falls back to `settings` when no profile is set.
    ws = wb[run_paths.sheet_for(wb, "settings")]
    s = {}
    for row in ws.iter_rows(min_row=2, values_only=True):
        if row[0]:
            s[str(row[0]).strip()] = row[1]
    out = {}
    for k, default, _ in DEFAULTS:
        v = s.get(k, default)
        out[k] = default if v is None else v
    out["cell_size_mm"] = float(out["cell_size_mm"])
    out["n_sample_points"] = int(out["n_sample_points"])
    out["random_seed"] = int(out["random_seed"])
    out["boundary_skin_frac"] = float(out["boundary_skin_frac"])
    out["max_file_mb"] = float(out["max_file_mb"])
    for k in ("thickness_cap_factor", "thickness_cap_fallback",
              "normal_axis_tol"):
        out[k] = float(out[k])
    out["min_thickness_hits"] = int(out["min_thickness_hits"])
    out["thickness_convention"] = str(out["thickness_convention"]).strip().lower()
    # resolve relative paths against this script's folder, and make sure the
    # output folder exists (outputs/ is not tracked, so it may be absent)
    p = str(out["stl_folder"])
    out["stl_folder"] = os.path.normpath(p if os.path.isabs(p) else os.path.join(BASE_DIR, p))
    # features are a DERIVED INPUT for later steps -> always land in ML/data/
    out["output_csv"] = run_paths.data_path(out["output_csv"])
    return out


# ------------------------------------------------------------------
# filename parameter parsing (best effort, generic)
# ------------------------------------------------------------------
def parse_params(stem, S=None):
    """Pull design parameters out of the filename using USER-SUPPLIED regexes.

    The five slots (inner, density, t, seed, multi) are generic - map whatever
    your filenames encode onto them via the 'filename_params' setting. Nothing
    about the ADMS naming scheme is assumed here.

    Format:   slot:regex ; slot:regex ; ...
    A regex with TWO capture groups is read as  group1.group2  (so the common
    "22p85" -> 22.85 convention works); ONE group is taken literally.

    ADMS default:  inner:i(\\d+)p(\\d+); density:d(\\d+)p(\\d+); t:t(\\d+)p(\\d+);
                   seed:_s(\\d+); multi:m(\\d+)p(\\d+)
    A TPMS user might instead write:
                   density:vf([0-9.]+); t:th([0-9.]+); seed:seed(\\d+)

    Slots left unmatched come out blank - that is not an error, it only means
    those columns are empty for this dataset.
    """
    p = {"inner": "", "density": "", "t": "", "seed": "", "multi": ""}
    spec = (S or {}).get("filename_params", "") if S else ""
    if not str(spec).strip():
        spec = DEFAULT_FILENAME_PARAMS
    for part in str(spec).split(";"):
        if ":" not in part:
            continue
        slot, rx = part.split(":", 1)
        slot, rx = slot.strip(), rx.strip()
        if slot not in p or not rx:
            continue
        try:
            m = re.search(rx, stem)
        except re.error:
            continue
        if not m:
            continue
        g = [x for x in m.groups() if x is not None]
        p[slot] = f"{g[0]}.{g[1]}" if len(g) >= 2 else (g[0] if g else "")
    return p


# ------------------------------------------------------------------
# geometry (numpy/scipy only - no rtree, no trimesh sampling/curvature)
# ------------------------------------------------------------------
def load_welded(path):
    """Load STL and weld duplicate vertices (needed for curvature)."""
    import trimesh
    m = trimesh.load(path, process=False)
    if hasattr(m, "geometry"):  # Scene
        m = trimesh.util.concatenate(list(m.geometry.values()))
    m.merge_vertices()
    return m


def interior_vertex_mask(V, bounds, skin_frac):
    bmin, bmax = bounds
    skin = skin_frac * (bmax - bmin)
    lo, hi = bmin + skin, bmax - skin
    return np.all((V > lo) & (V < hi), axis=1)


def gaussian_curvature(mesh, interior):
    """Angle-defect Gaussian curvature per interior vertex: K = defect / A_dual.

    Returns (K, weight) where weight is the dual area. THE WEIGHT MATTERS - the
    average of K must be AREA-WEIGHTED, sum(K*w)/sum(w). See the note at the
    curv_* row assignments below.
    """
    defects = np.asarray(mesh.vertex_defects)          # 2*pi - sum(angles)
    # dual area: 1/3 of adjacent face areas per vertex
    A = np.zeros(len(mesh.vertices))
    np.add.at(A, mesh.faces.ravel(),
              np.repeat(mesh.area_faces / 3.0, 3))
    ok = interior & (A > 1e-12)
    return defects[ok] / A[ok], A[ok]


def mean_curvature(mesh, interior):
    """Dihedral-angle mean curvature per interior edge:
       H = (0.5 * theta * len) / A_edge,  A_edge = 1/3 of the two adjacent faces.

    Returns (H, weight) where weight is A_edge - see gaussian_curvature.

    SIGN: convex -> POSITIVE, the standard outward-normal convention.
    SETTLED 2026-07-31 on shapes with known answers, so this needs no nTop run:
        sphere R=5  (convex everywhere)  analytic |H| = 1/R      = 0.20000
        torus R=10 r=3                   analytic avg|H| = 1/2r  = 0.16667
    This convention returns +0.20004 and +0.16670 - correct sign and magnitude
    to 0.02%. The previous code negated it and returned -0.20004 / -0.16670.

    History: the negation was added 2026-07-30 after checking against nTop's
    SI_Mean / SI_Area (a Surface Integral). That check was honest but the two nTop
    routes disagree - `Evaluate Field -> Curvature[Mean]`, which the 130-geometry
    validation and the master sheet's MeanCurv_STL both use, follows the convention
    below. nTop also matched the POSITIVE analytic torus value to 0.36%.

    Only `curv_mean_mean_xL` is affected. `curv_mean_iqr_xL` is a spread so it is
    sign-invariant, and `curv_mean_p99_xL` is taken on |H|. No model feature moves.
    """
    theta = np.asarray(mesh.face_adjacency_angles)     # dihedral angle per adjacent pair
    edges = np.asarray(mesh.face_adjacency_edges)
    elen = np.linalg.norm(mesh.vertices[edges[:, 0]] - mesh.vertices[edges[:, 1]], axis=1)
    pairs = np.asarray(mesh.face_adjacency)
    A_e = (mesh.area_faces[pairs[:, 0]] + mesh.area_faces[pairs[:, 1]]) / 3.0
    # sign of curvature from convexity (convex = positive - see docstring)
    convex = np.asarray(mesh.face_adjacency_convex)
    sign = np.where(convex, 1.0, -1.0)
    ok = interior[edges[:, 0]] & interior[edges[:, 1]] & (A_e > 1e-12)
    return sign[ok] * 0.5 * theta[ok] * elen[ok] / A_e[ok], A_e[ok]


def wall_thickness(mesh, interior, n_pts, cap_mm, seed):
    """Opposite-wall distance via cone search along the inward normal.

    For each sampled interior vertex p (normal n): find ALL vertices within
    cap_mm, keep those lying inside a cone along -n (direction cosine > 0.6)
    whose own normal opposes n (dot < -0.3), and take the NEAREST -> local
    wall thickness. Nearest-in-cone cannot jump across a pore, because the
    true opposite face is always closer than any face beyond the pore."""
    from scipy.spatial import cKDTree
    rng = np.random.default_rng(seed)
    V = np.asarray(mesh.vertices)
    N = np.asarray(mesh.vertex_normals)
    idx_int = np.flatnonzero(interior)
    if len(idx_int) == 0:
        return np.array([])
    sample = rng.choice(idx_int, size=min(n_pts, len(idx_int)), replace=False)
    tree = cKDTree(V)
    balls = tree.query_ball_point(V[sample], r=cap_mm)
    th = []
    for i, cand in enumerate(balls):
        if len(cand) < 2:
            continue
        p, n = V[sample[i]], N[sample[i]]
        cand = np.asarray(cand)
        vec = V[cand] - p
        d = np.linalg.norm(vec, axis=1)
        ok = d > 1e-3
        if not ok.any():
            continue
        dir_cos = -(vec[ok] @ n) / d[ok]          # 1.0 = straight along -n
        opposing = (N[cand[ok]] @ n) < -0.3
        m = (dir_cos > 0.6) & opposing
        if m.any():
            th.append(float(d[ok][m].min()))
    return np.array(th)


def fabric_tensor(mesh, skin_frac, axis_tol=0.9):
    """Area-weighted orientation tensor of the surface normals.

    WHY THIS EXISTS
    ---------------
    Every other feature in this file is a rotation-invariant scalar (volume
    fraction, mean curvature, wall thickness...). None of them can tell X from
    Z. TAI and the Zener ratio are DIRECTIONAL quantities, so predicting them
    from direction-blind inputs is impossible in principle - and that is why
    the 8-feature model scored only R2=0.615 on TAI, losing to three numbers
    typed into nTop (R2=0.747).

    The fabric tensor is the standard descriptor of structural anisotropy in
    porous media (Cowin 1985; Odgaard 1997, trabecular bone), and it is what
    relates morphology to the elastic anisotropy of a cellular solid:

        N = sum_i A_i (n_i (x) n_i) / sum_i A_i

    with A_i the face area and n_i the unit face normal. Eigenvalues sum to 1.
    Perfectly isotropic -> (1/3, 1/3, 1/3). Degree of anisotropy DA = l1/l3 is
    1.0 for isotropic and grows with directional bias.

    CUT-FACE EXCLUSION (critical)
    -----------------------------
    The unit cube's six outer faces are flat planes with normals exactly +-X,
    +-Y, +-Z and large area. Including them would swamp the tensor with the
    bounding box instead of the lattice. Faces whose centroid sits within
    skin_frac of a bbox wall AND whose normal is axis-aligned there are
    dropped, the same skin convention used for curvature.
    """
    V = np.asarray(mesh.vertices)
    F = np.asarray(mesh.faces)
    A = np.asarray(mesh.area_faces)
    Nrm = np.asarray(mesh.face_normals)
    bmin, bmax = mesh.bounds
    skin = skin_frac * (bmax - bmin)

    cent = V[F].mean(axis=1)
    keep = np.ones(len(F), dtype=bool)
    for ax in range(3):
        near_lo = cent[:, ax] < bmin[ax] + skin[ax]
        near_hi = cent[:, ax] > bmax[ax] - skin[ax]
        axis_aligned = np.abs(Nrm[:, ax]) > axis_tol
        keep &= ~((near_lo | near_hi) & axis_aligned)

    if keep.sum() < 100:
        return None
    A, Nrm = A[keep], Nrm[keep]
    N = (Nrm[:, :, None] * Nrm[:, None, :] * A[:, None, None]).sum(axis=0) / A.sum()
    ev = np.linalg.eigvalsh(N)[::-1]          # descending
    ev = np.clip(ev, 1e-12, None)
    # normals along an axis mean surface FACING that axis, i.e. material
    # oriented perpendicular to it - keep the raw diagonal too, it is the
    # directly interpretable per-axis quantity.
    diag = np.diag(N)
    return dict(l1=float(ev[0]), l2=float(ev[1]), l3=float(ev[2]),
                DA=float(ev[0] / ev[2]),
                nx=float(diag[0]), ny=float(diag[1]), nz=float(diag[2]),
                kept_frac=float(keep.mean()))


def extract_one(path, stem, S):
    t0 = time.time()
    L = S["cell_size_mm"]
    mesh = load_welded(path)

    bounds = mesh.bounds
    bbox = bounds[1] - bounds[0]
    vbox = float(np.prod(bbox))
    vol = float(abs(mesh.volume))
    area = float(mesh.area)

    row = {"dataset": S["dataset_tag"], "file": os.path.basename(path)}
    p = parse_params(stem, S)
    row.update({"inner": p["inner"], "density_param": p["density"],
                "t_input": p["t"], "seed": p["seed"], "size_multi": p["multi"]})
    row["bbox_mm"] = round(float(bbox[0]), 3)
    row["n_tris"] = len(mesh.faces)
    # VF comes from mesh.volume, which is ONLY valid on a closed, consistently
    # wound mesh. Record it per file rather than spot-checking a few: a leaky
    # mesh yields a silently wrong volume, and VF is the single most important
    # feature (r=0.967 with stiffness). Checked on 3 files 2026-07-20 (all
    # watertight); this column proves it for the whole dataset.
    try:
        row["watertight"] = int(bool(mesh.is_watertight))
        row["winding_ok"] = int(bool(mesh.is_winding_consistent))
        row["euler"] = int(mesh.euler_number)
    except Exception:
        row["watertight"] = ""; row["winding_ok"] = ""; row["euler"] = ""
    row["VF"] = round(vol / vbox, 5)
    row["SAV_x_cell"] = round(area / vol * L, 4)
    row["rel_surface"] = round(area / vbox * L, 4)

    interior = interior_vertex_mask(np.asarray(mesh.vertices), bounds,
                                    S["boundary_skin_frac"])
    row["interior_vert_frac"] = round(float(interior.mean()), 3)

    K, Kw = gaussian_curvature(mesh, interior)
    H, Hw = mean_curvature(mesh, interior)

    # AREA-WEIGHTED AVERAGE - do not use np.mean() here.
    #
    # K is a per-vertex RATIO (angle defect / dual area) and H a per-edge ratio.
    # A plain np.mean() of ratios weights every element equally, so it is
    # dominated by the SMALLEST triangles in the mesh - which is noise, and the
    # sign of that noise is arbitrary. nTop reports SI_Gauss/SI_Area, i.e. the
    # area-weighted average, and that is the physically meaningful quantity.
    #
    # Measured 2026-07-30 against nTop on 11 geometries (nTop values taken from
    # exported implicit bodies, verified exact to 8 dp):
    #     gaussian   np.mean()      r = -0.253   (no relationship at all)
    #                area-weighted  r = +0.817,  ratio to nTop  1.080
    #     mean curv  np.mean()      r = -0.914
    #                area-weighted  r = -0.946   (sign fixed in mean_curvature)
    # The plain mean was the reason curvature disagreed with nTop in sign on
    # 7 of 11 geometries while volume fraction and thickness both matched to
    # better than 1%.
    def area_avg(v, w):
        return float(np.sum(v * w) / np.sum(w))

    # Curvature SPREAD is reported as the interquartile range, not std.
    #
    # Validated 2026-07-20 on an identical gyroid meshed at 130k -> 964k faces:
    #     curv_mean_std   drifted +27.0%   (and H_max +211%)
    #     curv_mean_iqr   drifted  -0.5%
    # Marching cubes leaves a few near-degenerate triangles whose dihedral
    # angles are enormous. std() is dominated by those tails, so it partly
    # measures the MESH rather than the geometry - fatal here, because the
    # dataset spans 1M-9M triangles. The IQR ignores the tails and is stable.
    # This also cured the skew-10 warning from validate_dataset.py.
    #
    # The p99 columns are kept as a DIAGNOSTIC of outlier severity; they are
    # not intended as model features.
    def iqr(a):
        return float(np.subtract(*np.percentile(a, [75, 25])))

    row["curv_gauss_mean_xL2"] = round(area_avg(K, Kw) * L * L, 5)
    row["curv_gauss_iqr_xL2"]  = round(iqr(K) * L * L, 5)
    row["curv_mean_mean_xL"]   = round(area_avg(H, Hw) * L, 5)
    row["curv_mean_iqr_xL"]    = round(iqr(H) * L, 5)
    # diagnostics (mesh-quality monitors, not features)
    row["curv_gauss_p99_xL2"]  = round(float(np.percentile(np.abs(K), 99)) * L * L, 4)
    row["curv_mean_p99_xL"]    = round(float(np.percentile(np.abs(H), 99)) * L, 4)

    t_in = float(p["t"]) if p["t"] else None
    conv = S["thickness_convention"]
    expected = (t_in if conv == "total" else 2.0 * t_in) if (t_in and conv != "none") else None
    cap = (float(S["thickness_cap_factor"]) * expected if expected
           else float(S["thickness_cap_fallback"]) * L)
    th = wall_thickness(mesh, interior, S["n_sample_points"], cap, S["random_seed"])
    if len(th) > int(S["min_thickness_hits"]):
        t_med = float(np.median(th))
        row["thickness_med_mm"] = round(t_med, 4)
        row["thickness_std_mm"] = round(float(np.std(th)), 4)
        row["thickness_hits"] = len(th)
        row["thickness_over_cell"] = round(t_med / L, 5)
        row["thickness_ratio"] = round(t_med / expected, 3) if expected else ""
    else:
        row["thickness_med_mm"] = ""; row["thickness_std_mm"] = ""
        row["thickness_hits"] = len(th)
        row["thickness_over_cell"] = ""; row["thickness_ratio"] = ""

    # --- directional features (the only ones that can predict anisotropy) ---
    fab = fabric_tensor(mesh, S["boundary_skin_frac"],
                        float(S["normal_axis_tol"]))
    if fab:
        row["fabric_l1"] = round(fab["l1"], 5)
        row["fabric_l2"] = round(fab["l2"], 5)
        row["fabric_l3"] = round(fab["l3"], 5)
        row["fabric_DA"] = round(fab["DA"], 5)
        row["fabric_aniso"] = round(fab["l1"] - fab["l3"], 5)   # 0 = isotropic
        row["normal_x"] = round(fab["nx"], 5)
        row["normal_y"] = round(fab["ny"], 5)
        row["normal_z"] = round(fab["nz"], 5)
        # spread of the per-axis normal density; 0 when perfectly isotropic
        row["normal_spread"] = round(
            float(np.std([fab["nx"], fab["ny"], fab["nz"]])), 5)
        row["fabric_kept_frac"] = round(fab["kept_frac"], 3)
    else:
        for k in ("fabric_l1", "fabric_l2", "fabric_l3", "fabric_DA",
                  "fabric_aniso", "normal_x", "normal_y", "normal_z",
                  "normal_spread", "fabric_kept_frac"):
            row[k] = ""

    row["extract_s"] = round(time.time() - t0, 1)
    row["status"] = "OK"
    return row


def _topo_of(rel_path):
    """Immediate parent folder of an STL, relative to stl_folder. '' for a flat layout."""
    d = os.path.dirname(rel_path)
    return os.path.basename(d) if d else ""


FIELDS = ["dataset", "file", "topology", "inner", "density_param", "t_input", "seed",
          "size_multi", "bbox_mm", "n_tris",
          "watertight", "winding_ok", "euler",
          "VF", "SAV_x_cell", "rel_surface",
          "interior_vert_frac",
          "curv_gauss_mean_xL2", "curv_gauss_iqr_xL2",
          "curv_mean_mean_xL", "curv_mean_iqr_xL",
          "curv_gauss_p99_xL2", "curv_mean_p99_xL",
          "thickness_med_mm", "thickness_std_mm", "thickness_hits",
          "thickness_over_cell", "thickness_ratio",
          # directional / fabric-tensor features (anisotropy predictors)
          "fabric_l1", "fabric_l2", "fabric_l3", "fabric_DA", "fabric_aniso",
          "normal_x", "normal_y", "normal_z", "normal_spread",
          "fabric_kept_frac",
          "extract_s", "status"]


def main():
    S = load_settings()

    # ---- CLI overrides -------------------------------------------------------
    # The workbook holds the ADMS defaults. A partner dataset (Zhezhe's TPMS) needs
    # a different folder, cell size and thickness convention - but editing the
    # workbook to run it, then editing it back, is exactly how two datasets end up
    # extracted with different settings and nobody notices. Overriding on the
    # command line keeps ONE canonical workbook and makes each run self-describing.
    #   --stl-folder --output-csv --dataset-tag --cell-size --thickness-convention
    def _arg(flag, cast=str):
        if flag in sys.argv:
            i = sys.argv.index(flag)
            if len(sys.argv) > i + 1:
                return cast(sys.argv[i + 1])
        return None
    _ov = {"stl_folder": _arg("--stl-folder"),
           "output_csv": _arg("--output-csv"),
           "dataset_tag": _arg("--dataset-tag"),
           "cell_size_mm": _arg("--cell-size", float),
           "thickness_convention": _arg("--thickness-convention"),
           "max_file_mb": _arg("--max-file-mb", float)}
    applied = []
    for k, v in _ov.items():
        if v is None:
            continue
        if k == "stl_folder":
            v = os.path.normpath(v if os.path.isabs(v) else os.path.join(BASE_DIR, v))
        elif k == "output_csv":
            v = run_paths.data_path(v)
        elif k == "thickness_convention":
            v = str(v).strip().lower()
        applied.append(f"{k}={v}")
        S[k] = v
    if applied:
        print("[override] " + "   ".join(applied))

    test_n = None
    if "--test" in sys.argv:
        i = sys.argv.index("--test")
        test_n = int(sys.argv[i + 1]) if len(sys.argv) > i + 1 else 3

    stl_dir, out_csv = str(S["stl_folder"]), str(S["output_csv"])
    # Recursive: ADMS STLs sit flat in one folder, the partner's TPMS STLs sit in
    # one subfolder per topology. The immediate parent folder name becomes the
    # `topology` column (empty for a flat layout, so ADMS behaviour is unchanged).
    files = []
    for _root, _dirs, _fs in os.walk(stl_dir):
        for _f in _fs:
            if _f.lower().endswith(".stl"):
                files.append(os.path.relpath(os.path.join(_root, _f), stl_dir))
    files = sorted(files)
    if not files:
        print(f"[!] no STL files in {stl_dir}"); return
    _nsub = sum(1 for r in files if os.path.dirname(r))
    if _nsub:
        print(f"[ok] {len(files)} STLs, {_nsub} inside topology subfolders")

    done = set()
    if os.path.exists(out_csv):
        with open(out_csv, newline="", encoding="utf-8") as f:
            done = {(str(r.get("topology", "")), r["file"]) for r in csv.DictReader(f)
                    if not str(r.get("status", "")).startswith(("ERROR", "SKIP"))}
    # Refuse to append under a stale header. FIELDS gained `topology`; appending
    # new-order rows beneath an old header shifts every column silently.
    if os.path.exists(out_csv):
        with open(out_csv, newline="", encoding="utf-8") as _f:
            _hdr = next(csv.reader(_f), [])
        if _hdr and _hdr != FIELDS:
            sys.exit(f"[E] {out_csv} was written with a DIFFERENT column set.\n"
                     f"    on disk : {len(_hdr)} cols, starts {_hdr[:4]}\n"
                     f"    expected: {len(FIELDS)} cols, starts {FIELDS[:4]}\n"
                     f"    Appending would shift every column. Delete or rename that file "
                     f"and re-extract from scratch.")
    write_header = not os.path.exists(out_csv)
    out = open(out_csv, "a", newline="", encoding="utf-8")
    w = csv.DictWriter(out, fieldnames=FIELDS)
    if write_header:
        w.writeheader()

    todo = [r for r in files if (_topo_of(r), os.path.basename(r)) not in done]
    if test_n: todo = todo[:test_n]
    print(f"feature_extraction | dataset={S['dataset_tag']} cell={S['cell_size_mm']}mm "
          f"conv={S['thickness_convention']} seed={S['random_seed']}")
    print(f"{len(files)} STLs, {len(done)} done, {len(todo)} to process"
          + (f"  (TEST MODE {test_n})" if test_n else ""))

    for i, rel in enumerate(todo, 1):
        path = os.path.join(stl_dir, rel)
        f = os.path.basename(rel)
        topo = _topo_of(rel)
        mb = os.path.getsize(path) / 1e6
        if mb > S["max_file_mb"]:
            row = dict.fromkeys(FIELDS, "")
            row.update({"dataset": S["dataset_tag"], "file": f, "topology": topo,
                        "status": f"SKIPPED >{S['max_file_mb']}MB"})
            w.writerow(row); out.flush()
            print(f"[{i}/{len(todo)}] {f}  SKIPPED (>{S['max_file_mb']} MB)")
            continue
        try:
            row = extract_one(path, f[:-4], S)
            row["topology"] = topo
            w.writerow(row); out.flush()
            print(f"[{i}/{len(todo)}] {f}  VF={row['VF']}  "
                  f"t_med={row['thickness_med_mm']}  ratio={row['thickness_ratio']}  "
                  f"({row['extract_s']}s)")
        except Exception as e:
            row = dict.fromkeys(FIELDS, "")
            row.update({"dataset": S["dataset_tag"], "file": f, "topology": topo,
                        "status": f"ERROR {e}"})
            w.writerow(row); out.flush()
            print(f"[{i}/{len(todo)}] {f}  ERROR: {e}")

    out.close()
    print("\ndone. output:", out_csv)
    print("CHECK: thickness_ratio ~1.0 on every row = feature-accuracy validation.")


if __name__ == "__main__":
    main()
